# -*- coding: utf-8 -*-
from . import test_channel_config
from . import test_channel_list_module
from . import test_channel_product
from . import test_product_template_channel
from . import test_controllers
from . import test_video_connector
from . import test_image_connector
from . import test_controller_routes
from . import test_channel_order
from . import test_price_recommendation
from . import test_channel_product_variant
from . import test_channel_product_attribute
from . import test_channel_product_field_mapping
from . import test_category_mapping
from . import test_sale_order_channel
from . import test_product_product_channel
from . import test_shopee_connector
from . import test_lazada_connector
from . import test_tiktok_connector
from . import test_crons
from . import test_oauth
from . import test_wizards
from . import test_mixins
from . import test_security
from . import test_webhooks
from . import test_reports
from . import test_i18n
from . import test_channel_order_line
from . import test_channel_product_attribute
